Prashna Prajapati

Problem-1:

Array Creations:

1) Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

# Create an empty array 2x2
empty_array = np.empty((2, 2))
print(empty_array)


[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


 2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np

# Create a 4x2 array filled with ones
ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np

# Create an array with shape (3, 3), filled with the value 7
filled_array = np.full((3, 3), 7)
print(filled_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np

# Given array
given_array = np.array([[1, 2], [3, 4]])

# Create a new array of zeros with the same shape and type as given_array
zeros_like_array = np.zeros_like(given_array)
print(zeros_like_array)

[[0 0]
 [0 0]]


 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np

# Given array
given_array = np.array([[4, 5, 6], [7, 8, 9]])

# Create a new array of ones with the same shape and type as given_array
ones_like_array = np.ones_like(given_array)
print(ones_like_array)

[[1 1 1]
 [1 1 1]]


 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# Existing list
new_list = [1, 2, 3, 4]

# Convert the list to a NumPy array
array_from_list = np.array(new_list)

print(array_from_list)

[1 2 3 4]


Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:

 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

# Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print(array_10_to_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


 2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}

In [ ]:
import numpy as np

#Create a 3X3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)

print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np

# Create a random array of size 30
random_array = np.random.random(30)

# Calculate the mean of the array
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Mean of the Array:", mean_value)

Random Array: [0.05303045 0.60716888 0.73889803 0.02911853 0.00860651 0.71794431
 0.46452535 0.48439448 0.55740939 0.02274102 0.52381138 0.62453986
 0.38089192 0.48148786 0.75506708 0.07401507 0.84250744 0.65383067
 0.79586933 0.96574731 0.89178794 0.52570154 0.95138101 0.43115533
 0.70188834 0.5556834  0.88894284 0.73491901 0.64957839 0.14736337]
Mean of the Array: 0.5420002001289681


 5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np

# Create a 10x10 array with random values between 0 and 1
random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Random 10x10 Array:
[[0.82159494 0.98054272 0.93642867 0.55035874 0.55993028 0.9979233
  0.00773004 0.37024922 0.22900749 0.38492026]
 [0.75135218 0.5814187  0.79537579 0.26609524 0.59639767 0.09455982
  0.80381327 0.12926728 0.84348652 0.50968787]
 [0.98896305 0.58547391 0.94868306 0.92890211 0.23116665 0.52159553
  0.43418094 0.50762999 0.5484875  0.45433735]
 [0.82842545 0.11460579 0.38854443 0.44274977 0.36647115 0.30329657
  0.67951442 0.42273049 0.10559289 0.91820717]
 [0.78181798 0.25560676 0.89263101 0.27464058 0.68931553 0.65794166
  0.89464704 0.77555847 0.87968767 0.5211395 ]
 [0.20314473 0.84686057 0.94446256 0.70982051 0.70685235 0.71741894
  0.60603686 0.53125214 0.21867216 0.76844256]
 [0.47121349 0.54840327 0.41648189 0.96335644 0.51702332 0.57865904
  0.58289727 0.8514991  0.37568568 0.54685607]
 [0.26159947 0.92330372 0.98109489 0.81066826 0.31668028 0.90701526
  0.43655199 0.78939445 0.79319553 0.559313  ]
 [0.14323539 0.98837485 0.6479608  0.08167557 0.9718591  0.60

 6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np

# Create a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
zero_array[4] = 1

print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np

# Given array
arr = np.array([1, 2, 0, 0, 4, 0])

# Reverse the array using slicing
reversed_arr = arr[::-1]

print(reversed_arr)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np

# Define the size of the array (e.g., 5x5)
size = 5

# Create a 2D array filled with zeros
array = np.zeros((size, size), dtype=int)

# Set the border elements to 1
array[0, :] = 1  # Set top row to 1
array[-1, :] = 1  # Set bottom row to 1
array[:, 0] = 1  # Set left column to 1
array[:, -1] = 1  # Set right column to 1

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# Create an 8x8 matrix filled with zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern with 1s
checkerboard[1::2, ::2] = 1  # Set 1s in the alternating columns for even rows
checkerboard[::2, 1::2] = 1  # Set 1s in the alternating columns for odd rows

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 Problem- 3: Array Operations:

 For the following arrays:
 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12]);

 1. Add the two array.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Add the two arrays
sum_array = np.add(x, y)

print(sum_array)

[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Subtract the two arrays
diff_array = np.subtract(x, y)

print(diff_array)

[[-4 -4]
 [-4 -3]]


 3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

#Multiply the array
multiplied_array_x = np.multiply(x, 2)
multiplied_array_y = np.multiply(y, 4)


print(multiplied_array_x)
print(multiplied_array_y)

[[ 2  4]
 [ 6 10]]
[[20 24]
 [28 32]]


 4. Find the square of each element of the array.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

#square of each element of the array.
squared_array_x = np.square(x)
squared_array_y = np.square(y)

print(squared_array_x)
print(squared_array_y)


[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])  # 2x2 array
y = np.array([[5, 6], [7, 8]])  # 2x2 array
v = np.array([9, 10])           # 1D array
w = np.array([11, 12])          # 1D array

# Dot product of v and w (1D arrays)
dot_v_w = np.dot(v, w)

# Dot product of x and v (2D array x and 1D array v)
dot_x_v = np.dot(x, v)

# Dot product of x and y (2D array x and 2D array y)
dot_x_y = np.dot(x, y)

# Print the results
print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:", dot_x_v)
print("Dot product of x and y:", dot_x_y)


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])  # 2x2 array
y = np.array([[5, 6], [7, 8]])  # 2x2 array
v = np.array([9, 10])           # 1D array
w = np.array([11, 12])          # 1D array

# Concatenate x and y along rows (axis=0)
concat_x_y = np.concatenate((x, y), axis=0)  # Or you can use np.vstack((x, y))

# Concatenate v and w along columns (axis=1)
# Reshape v and w from 1D to 2D before concatenating
v_reshaped = v.reshape(-1, 1)  # Convert v to a 2D column vector
w_reshaped = w.reshape(-1, 1)  # Convert w to a 2D column vector
concat_v_w = np.concatenate((v_reshaped, w_reshaped), axis=1)  # Or use np.hstack((v_reshaped, w_reshaped))

# Print the results
print("Concatenated x and y along rows:")
print(concat_x_y)

print("\nConcatenated v and w along columns:")
print(concat_v_w)

Concatenated x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenated v and w along columns:
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

try:
  concat_x_v = np.concatenate((x, v), axis=1)
except ValueError as e:
  print(f"Error: {e}")

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


 Problem- 4:

 Matrix Operations:

 • For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:
 1. Prove A.A−1 = I.

In [ ]:
import numpy as np

# Define matrix A
A = np.array([[4, 7], [2, 6]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by its inverse
result = np.dot(A, A_inv)

# Output the result
print("A.A⁻¹ =\n", result)

A.A⁻¹ =
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


2.Prove AB=/= BA.

In [ ]:
import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Calculate AB
AB = np.dot(A, B)

# Calculate BA
BA = np.dot(B, A)

# Compare AB and BA
print("AB =\n", AB)
print("\nBA =\n", BA)

if np.array_equal(AB, BA):
    print("\nAB = BA")
else:
    print("\nAB =/= BA")

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

AB =/= BA


3. Prove (AB)T = BTAT.

In [ ]:
import numpy as np
# Compute (AB)^T
AB_T = np.transpose(np.dot(A, B))

# Compute B^T and A^T
B_T = np.transpose(B)
A_T = np.transpose(A)

# Compute B^T A^T
B_T_A_T = np.dot(B_T, A_T)

# Output the results
print("Transpose of AB =\n", AB_T)
print("B^T A^T =\n", B_T_A_T)

Transpose of AB =
 [ 16  20 -15]
B^T A^T =
 [ 16  20 -15]


 • Solve the following system of Linear equation using Inverse Methods.

 2x −3y+z =−1

 x −y+2z =−3

 3x +y−z =9

In [ ]:
import numpy as np
# Define matrix A (coefficients of the system)
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])

# Define matrix B (constants on the right side)
B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using the inverse of A
X = np.dot(A_inv, B)

# Output the solution
print("Solution X =\n", X)

Solution X =
 [ 2.  1. -2.]


 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
 of Numpy}

In [ ]:
import numpy as np

X_direct = np.linalg.solve(A, B)

print("Solution X using np.linalg.solve =\n", X_direct)

Solution X using np.linalg.solve =
 [ 2.  1. -2.]


Experiment: How Fast is Numpy?

 In this exercise, you will compare the performance and implementation of operations using plain Python
 lists (arrays) and NumPy arrays. Follow the instructions:
 1. Element-wise Addition:

 • Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
 and Print the time taken for this operation.

In [ ]:
import numpy as np
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]  # List with values from 1 to 1,000,000
list2 = [i for i in range(1000001, 2000001)]  # List with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform element-wise addition using a loop
result = [list1[i] + list2[i] for i in range(len(list1))]

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise addition: {end_time - start_time} seconds")


Time taken for element-wise addition: 0.17740130424499512 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
 operation.

In [ ]:
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)  # Array with values from 1 to 1,000,000
array2 = np.arange(1000001, 2000001)  # Array with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform element-wise addition using NumPy arrays
result = array1 + array2  # NumPy allows direct element-wise addition

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise addition using NumPy: {end_time - start_time} seconds")


Time taken for element-wise addition using NumPy: 0.034974098205566406 seconds


2. Element-wise Multiplication

 • Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Mea
sure and Print the time taken for this operation.

In [ ]:
import numpy as np
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]  # List with values from 1 to 1,000,000
list2 = [i for i in range(1000001, 2000001)]  # List with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform element-wise multiplication using a loop
result = [list1[i] * list2[i] for i in range(len(list1))]

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time} seconds")


Time taken for element-wise multiplication using Python lists: 0.1560657024383545 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
 operation.

In [ ]:
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)  # Array with values from 1 to 1,000,000
array2 = np.arange(1000001, 2000001)  # Array with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform element-wise multiplication using NumPy arrays
result = array1 * array2  # NumPy allows direct element-wise multiplication

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise multiplication using NumPy: {end_time - start_time} seconds")


Time taken for element-wise multiplication using NumPy: 0.0049974918365478516 seconds


3. Dot Product

 • Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and
 Print the time taken for this operation.

In [ ]:
import numpy as np
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]  # List with values from 1 to 1,000,000
list2 = [i for i in range(1000001, 2000001)]  # List with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform dot product using a loop (element-wise multiplication and sum)
dot_product = sum(list1[i] * list2[i] for i in range(len(list1)))

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for dot product using Python lists: {end_time - start_time} seconds")


Time taken for dot product using Python lists: 0.16859960556030273 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
 operation.

In [ ]:
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)  # Array with values from 1 to 1,000,000
array2 = np.arange(1000001, 2000001)  # Array with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform dot product using NumPy arrays
dot_product = np.dot(array1, array2)

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for dot product using NumPy: {end_time - start_time} seconds")


Time taken for dot product using NumPy: 0.0022211074829101562 seconds


4. Matrix Multiplication

 • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
 and print the time taken for this operation.

In [ ]:
import numpy as np
import time

# Create two 1000x1000 matrices
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]  # 1000x1000 matrix
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]  # 1000x1000 matrix

# Start measuring time
start_time = time.time()

# Perform matrix multiplication (result = matrix1 * matrix2)
result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time} seconds")


Time taken for matrix multiplication using Python lists: 248.00040817260742 seconds


• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea
sure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

# Create two 1000x1000 matrices with random values
matrix1 = np.random.rand(1000, 1000)  # 1000x1000 matrix with random values
matrix2 = np.random.rand(1000, 1000)  # 1000x1000 matrix with random values

# Start measuring time
start_time = time.time()

# Perform matrix multiplication using NumPy
result = np.dot(matrix1, matrix2)  # You can also use matrix1 @ matrix2

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for matrix multiplication using NumPy: {end_time - start_time} seconds")


Time taken for matrix multiplication using NumPy: 0.060072898864746094 seconds
